import Head from 'next/head'
import {GalleryNoSSR} from "@/components/Gallery";
import {Wizard} from "@/components/Wizard";

export default function Photobooth() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-row">
          <div className="flex-1 basis-1/3 overflow-y-auto bg-gray-100">
            <GalleryNoSSR />
          </div>
          <div className="flex-1 basis-2/3 bg-gray-300">
            <Wizard />
          </div>
      </main>
    </>
  )
}
